typeof '' // -> "String"
typeof 1 // -> "Number"
typeof NaN // -> "Number"
typeof true // -> "Boolean"
typeof undefined // -> "undefined"
typeof Symbol() // -> "Symbol"
typeof null // -> "object"
typeof [] // -> "object"
typeof {} // -> "object"
typeof new Date() // -> "object"
typeof /test/gi // -> "object"
typeof function() {} // -> "function"